model lp.mod;
data n_38_b_30_count_5_4.dat;

option solver cplex;
option cplex_options 'timelimit=60';
option cplex_options 'integrality=3e-07';
solve;

display _solve_elapsed_time > n_38_b_30_count_5_4_lp.out;
display calculated_sum > n_38_b_30_count_5_4_lp.out;
display target_sum > n_38_b_30_count_5_4_lp.out;
display set_len > n_38_b_30_count_5_4_lp.out;
display x > n_38_b_30_count_5_4_lp.out;
display values > n_38_b_30_count_5_4_lp.out;

