model ilp.mod;
data n_70_b_30_count_5_4.dat;

option solver cplex;
option cplex_options 'timelimit=60';
option cplex_options 'integrality=3e-07';
solve;

display _solve_elapsed_time > n_70_b_30_count_5_4_ilp.out;
display calculated_sum > n_70_b_30_count_5_4_ilp.out;
display target_sum > n_70_b_30_count_5_4_ilp.out;
display set_len > n_70_b_30_count_5_4_ilp.out;
display x > n_70_b_30_count_5_4_ilp.out;
display values > n_70_b_30_count_5_4_ilp.out;

