model ilp.mod;
data n_20_b_30_count_5_3.dat;

option solver cplex;
option cplex_options 'timelimit=60';
option cplex_options 'integrality=3e-07';
solve;

display _solve_elapsed_time > n_20_b_30_count_5_3_ilp.out;
display calculated_sum > n_20_b_30_count_5_3_ilp.out;
display target_sum > n_20_b_30_count_5_3_ilp.out;
display set_len > n_20_b_30_count_5_3_ilp.out;
display x > n_20_b_30_count_5_3_ilp.out;
display values > n_20_b_30_count_5_3_ilp.out;

