model lp.mod;
data n_2_b_30_count_5_0.dat;

option solver cplex;
option cplex_options 'timelimit=60';
option cplex_options 'integrality=3e-07';
solve;

display _solve_elapsed_time > n_2_b_30_count_5_0_lp.out;
display calculated_sum > n_2_b_30_count_5_0_lp.out;
display target_sum > n_2_b_30_count_5_0_lp.out;
display set_len > n_2_b_30_count_5_0_lp.out;
display x > n_2_b_30_count_5_0_lp.out;
display values > n_2_b_30_count_5_0_lp.out;

